services:
    backend:
        image: node:latest
        container_name: backend-container
        working_dir: /app
        ports:
            - 3001:3000
        volumes:
            - ./backend:/app
        networks:
            postgres-fiap-mobile:
        command: sh -c "npm i && npm run build && node dist/main"

networks:
    postgres-fiap-mobile:
        driver: bridge
        
